### ISSUE TITLE
반응형 레이아웃

### ISSUE THREAD

**Issue by minjeongHEO** [minjeongHEO/Job-Cracker#36]
## ✏️ 기능 설명
모바일에서도 사용할 수 있도록 반응형으로 레이아웃을 수정하고, iOS Safari에서의 높이 관련 이슈를 해결합니다.

## ✅ 개발 내용
1. 반응형 레이아웃 기본 설정
- [x] 미디어 스크린 적용하여 반응형 레이아웃 구현
- breakpoint 믹스인 설정으로 미디어 쿼리 관리 체계화

2. **모바일 높이 이슈 해결 과정**
- [x] iOS Safari, Chrome (모바일) 높이 이슈 해결
- 초기에는 `@supports (-webkit-touch-callout: none)`을 활용한 `ios-height-fix` 믹스인 적용
  - 모바일 주소창에 가려지는 이슈 해결을 위한 webkit CSS 속성값 추가
  - 각 컴포넌트에 믹스인 적용 및 수정
- 최종적으로 `dvh` 단위 사용으로 변경
  - iOS Safari에서 더 안정적인 높이 계산이 가능
  - 기존 믹스인 제거하고 높이값을 `dvh`로 통일

4. 레이아웃 및 UI 개선
- [x] PC 버전에서 위로 쏠리는 레이아웃 수정
- [x] 선택 버튼의 글자와 뱃지 줄바꿈 처리
- [x] 모바일에서 선택 페이지가 잘리는 문제 해결
- [x] 개발 선택 페이지에 스크롤 적용
- [x] 질문 답변 페이지의 모바일 화면 싱크 맞추기
- [x] 전송 버튼 아이콘 중앙 정렬

5. 사용성 개선
- [x] 모바일에서 input 입력 시 자동 확대 방지
- CSS 적용
  ```css
  input,
  {
    font-size: 16px; // iOS에서 16px 미만일 때 자동 확대되는 것을 방지
    -webkit-text-size-adjust: 100%; // 텍스트 크기 자동 조정 방지
    touch-action: manipulation; // 터치 동작 최적화
  }
  ```
  - viewport meta 태그 방법도 있었지만 CSS로 처리하여 웹 접근성 유지
시각장애가 있는 사용자의 접근성을 제한할 수 있으므로, input, textarea 태그에만 확대 방지 적용

## 📕 참고 사항
- `dvh` 단위는 모바일 브라우저의 동적 viewport 높이를 더 정확하게 계산
- iOS Safari에서 주소창으로 인한 높이 계산 이슈는 흔한 문제
- input 자동 확대 방지를 위해 웹 접근성을 고려한 CSS 방식 채택
