### ISSUE TITLE
로딩 처리

### ISSUE THREAD

**Issue by minjeongHEO** [minjeongHEO/Job-Cracker#41]
## ✏️ 기능 설명
질문 생성 및 답변 피드백 API 요청 중일 때의 로딩 상태 처리 구현
- API 요청 중 사용자 입력 방지
- 시각적 피드백 제공
<br><br>

## ✅ TODO
- [x] 로딩 상태 통합 관리
  - 질문 생성 중: 'question'
  - 답변 피드백 중: 'feedback'
  - 작업 끝: null
- [x] 로딩 중 UI 처리
  - [x] Input 비활성화 및 placeholder 변경
  - [x] 전송 버튼 비활성화
  - [x] '다른 주제' 버튼 비활성화
- [x] 로딩 스피너 구현
<br><br>

### LoadingType을 통한 상태 관리
단일 LoadingType으로 여러 로딩 상태를 관리하면서도 각각의 상황에 맞는 메시지를 표시할 수 있도록 구현하였습니다.
```typescript
type LoadingType = 'question' | 'feedback' | null;

// 상태별 메시지 처리
const placeHolder = (loadingType: LoadingType, isMobile: boolean) => {
  if (loadingType === 'feedback') {
    return '답변을 검토 중입니다...';
  }
  if (loadingType === 'question') {
    return '질문을 생성 중입니다...';
  }
  return isMobile ? '답변을 입력해주세요' : '답변을 입력해주세요 (Shift + Enter로 줄바꿈)';
};
```

### 로딩 중 UI 처리
버튼의 경우, 사용자가 불필요한 버튼을 보지 않지만, 버튼이 갑자기 사라지고 생기는게 안좋다고 생각하여
```tsx
{isLastQuestion && loadingType == null && (
  <button onClick={handleGenerateAnotherQuestion}>
    다른 주제
  </button>
)}
```
버튼을 숨기는 것보다 비활성화 상태로 표시하는 것이 레이아웃 안정성과 상태 표시 측면에서 더 적절하다고 판단하였습니다.
disabled 상태와 함께 시각적 피드백을 제공하는 것이 UX 측면에서 더 좋은 것 같아 선택하였습니다.
```tsx
{isLastQuestion && (
  <button 
    onClick={handleGenerateAnotherQuestion}
    disabled={loadingType !== null}
  >
    다른 주제
  </button>
)}
```
```scss
&--new {
  &:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }
}
```
### 커스텀 로딩 스피너
UI 라이브러리 대신 CSS/SVG 기반 커스텀 로더를 사용하였습니다.
- 번들 사이즈 최적화
- 불필요한 의존성 제거
- 커스터마이징 용이

```scss
.loading-spinner {
  position: absolute;
  top: 45%;
  left: 47%;
  opacity: 0;
  z-index: 999;
  transition: opacity 0.1s ease-in;

  &--loading-animation {
    opacity: 1;
    animation: spin 1.5s linear infinite;
  }
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
```
